[package]
name = "juju"
description = "A library to interact with the Juju system. For an example charm see: https://github.com/cholcombe973/gluster-charm"
version = "0.1.4"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
repository = "https://github.com/cholcombe973/Juju"
license = "MIT"
